### PR TITLE
Finish Homework

### PR DESCRIPTION
**Pull request by VitoNaychev**
Checked most of them with the test inputs. Worked with them but not very sure if will work with other. 
Sad Pepe
cancer

### CODE REVIEW

**Comment by VitoNaychev** [comment]
Gr8 content m8! Keep up the good work!!!

**Comment by VitoNaychev** [comment]
Kys fgt. Nobody cares about your code. Here use this medieval invention to make the world a better place. 
kys

**Comment by VitoNaychev** [comment]
sry for cancer comments

**Comment by L3K0V** [comment]
Genady is coming soon with the big axe!

**Comment by VitoNaychev** [comment]
lmao

**Comment by L3K0V** [comment]
Настройвам го още, ще ме извиняваш...

**Comment by VitoNaychev** [comment]
Task 3 time restrictions?

**Comment by VitoNaychev** [comment]
окей

**Comment by VitoNaychev** [comment]
няма да мога да заспя сега

**Comment by L3K0V** [comment]
и аз... :(

**Comment by VitoNaychev** [comment]
sori motori genadi, ne moga da ti pomogna glavno 6tot ne znam kakvo lafi6

**Comment by bankin** [comment]
Нали е мърджнато? Нека си мрънка :)

**Pull request merged**
